"""Criacao inicial de todas as tabelas

Revision ID: 214a4eb1d911
Revises: 
Create Date: 2025-07-20 14:49:55.512906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214a4eb1d911'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empreendimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.String(length=250), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('publico', sa.Boolean(), nullable=False),
    sa.Column('prazo_entrega', sa.Date(), nullable=True),
    sa.Column('previsao_entrega', sa.String(length=255), nullable=True),
    sa.Column('valor_medio_unidades', sa.String(length=255), nullable=True),
    sa.Column('valor_a_partir_de', sa.String(length=255), nullable=True),
    sa.Column('tamanho_terreno', sa.String(length=255), nullable=True),
    sa.Column('quantidade_torres', sa.Integer(), nullable=True),
    sa.Column('subsolos', sa.Integer(), nullable=True),
    sa.Column('andares', sa.Integer(), nullable=True),
    sa.Column('campanha_promocional', sa.Text(), nullable=True),
    sa.Column('arquiteto', sa.String(length=255), nullable=True),
    sa.Column('paisagismo', sa.String(length=255), nullable=True),
    sa.Column('decoracao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exemplo_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto_documento', sa.Text(), nullable=False),
    sa.Column('json_resultado_corrigido', sa.Text(), nullable=False),
    sa.Column('instrucao_correcao', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('_senha_hash', sa.String(length=256), nullable=False),
    sa.Column('perfil', sa.Enum('ADMIN', 'CORRETOR', name='perfilusuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('profissao', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('email_comercial', sa.String(length=120), nullable=True),
    sa.Column('ddd_pessoal', sa.String(length=2), nullable=False),
    sa.Column('telefone_pessoal', sa.String(length=9), nullable=False),
    sa.Column('ddd_pessoal_2', sa.String(length=2), nullable=True),
    sa.Column('telefone_pessoal_2', sa.String(length=9), nullable=True),
    sa.Column('ddd_residencial', sa.String(length=2), nullable=True),
    sa.Column('telefone_residencial', sa.String(length=9), nullable=True),
    sa.Column('ddd_comercial', sa.String(length=2), nullable=True),
    sa.Column('telefone_comercial', sa.String(length=9), nullable=True),
    sa.Column('cep_residencial', sa.String(length=9), nullable=True),
    sa.Column('logradouro_residencial', sa.String(length=200), nullable=True),
    sa.Column('numero_residencial', sa.String(length=20), nullable=True),
    sa.Column('complemento_residencial', sa.String(length=50), nullable=True),
    sa.Column('bairro_residencial', sa.String(length=100), nullable=True),
    sa.Column('cidade_residencial', sa.String(length=100), nullable=True),
    sa.Column('estado_residencial', sa.String(length=2), nullable=True),
    sa.Column('empresa_cliente', sa.String(length=150), nullable=True),
    sa.Column('endereco_comercial_cliente', sa.Text(), nullable=True),
    sa.Column('estado_civil', sa.Enum('SOLTEIRO', 'CASADO', 'DIVORCIADO', 'VIUVO', 'UNIAO_ESTAVEL', name='estadocivil'), nullable=True),
    sa.Column('nome_conjuge', sa.String(length=150), nullable=True),
    sa.Column('cpf_conjuge', sa.String(length=14), nullable=True),
    sa.Column('profissao_conjuge', sa.String(length=100), nullable=True),
    sa.Column('email_conjuge', sa.String(length=120), nullable=True),
    sa.Column('email_conjuge_comercial', sa.String(length=120), nullable=True),
    sa.Column('ddd_conjuge', sa.String(length=2), nullable=True),
    sa.Column('telefone_conjuge', sa.String(length=9), nullable=True),
    sa.Column('empresa_conjuge', sa.String(length=150), nullable=True),
    sa.Column('endereco_comercial_conjuge', sa.Text(), nullable=True),
    sa.Column('origem_lead', sa.String(length=100), nullable=True),
    sa.Column('data_primeiro_contato', sa.Date(), nullable=True),
    sa.Column('temperatura', sa.Enum('QUENTE', 'MORNO', 'FRIO', name='temperaturalead'), nullable=True),
    sa.Column('status', sa.Enum('LEAD_NOVO', 'EM_CONTATO', 'EM_NEGOCIACAO', 'COMPROU', 'DESCARTADO', name='statuscliente'), nullable=False),
    sa.Column('faixa_renda', sa.String(length=50), nullable=True),
    sa.Column('valor_imovel_buscado', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('descartado', sa.Boolean(), nullable=False),
    sa.Column('proprietario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proprietario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email_comercial')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_original', sa.String(length=200), nullable=False),
    sa.Column('nome_arquivo_servidor', sa.String(length=200), nullable=False),
    sa.Column('empreendimento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empreendimento_id'], ['empreendimento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_arquivo_servidor')
    )
    op.create_table('tipologia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metragem', sa.String(length=100), nullable=False),
    sa.Column('suites', sa.String(length=100), nullable=True),
    sa.Column('vagas', sa.String(length=100), nullable=True),
    sa.Column('empreendimento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empreendimento_id'], ['empreendimento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('empreendimento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['empreendimento_id'], ['empreendimento.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.Enum('LIGACAO', 'EMAIL', 'WHATSAPP', 'REUNIAO', 'VISITA', 'FOLLOW_UP', 'OUTRO', name='tipoatividade'), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interesses',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('empreendimento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['empreendimento_id'], ['empreendimento.id'], ),
    sa.PrimaryKeyConstraint('cliente_id', 'empreendimento_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interesses')
    op.drop_table('atividade')
    op.drop_table('agendamento')
    op.drop_table('tipologia')
    op.drop_table('material')
    op.drop_table('cliente')
    op.drop_table('usuario')
    op.drop_table('exemplo_ia')
    op.drop_table('empreendimento')
    # ### end Alembic commands ###
